# Generated by Django 6.0.3 on 2026-03-27 07:20

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PatientAssessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patient_name', models.CharField(blank=True, default='Anonymous', max_length=100)),
                ('patient_age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('mmse_score', models.FloatField()),
                ('cdr_score', models.FloatField()),
                ('education_years', models.FloatField()),
                ('socioeconomic_status', models.IntegerField()),
                ('etiv', models.FloatField()),
                ('nwbv', models.FloatField()),
                ('asf', models.FloatField()),
                ('memory_score', models.FloatField()),
                ('attention_score', models.FloatField()),
                ('language_score', models.FloatField()),
                ('visuospatial_score', models.FloatField()),
                ('family_history', models.BooleanField(default=False)),
                ('apoe4_alleles', models.IntegerField(choices=[(0, '0 alleles'), (1, '1 allele'), (2, '2 alleles')], default=0)),
                ('prediction', models.CharField(blank=True, choices=[('healthy', 'Cognitively Normal'), ('mci', 'Mild Cognitive Impairment'), ('alzheimer', "Alzheimer's Disease")], max_length=20)),
                ('confidence_healthy', models.FloatField(default=0.0)),
                ('confidence_mci', models.FloatField(default=0.0)),
                ('confidence_alzheimer', models.FloatField(default=0.0)),
                ('risk_score', models.FloatField(default=0.0)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
